### ISSUE TITLE
Getting error while executing 

### ISSUE THREAD

**Issue by noufanpmc** [vadi95/Signature-Verification#1]
Hai I'm getting error when I ran your code, I did'nt made any changes, I just want to learn how the working and downloaded the repository and just executed run.py.

But its showing this error
ValueError: Cannot take a larger sample than population when 'replace=False'

Can you please help to solve this issue. I'm new to python, it'll be a great help for my learning phase.

**Comment by Kanon11** [comment]
replace the value of k=500 to 200, then it should be work.

**Comment by noufanpmc** [comment]
Thank you so much.
It worked.

**Comment by hp321** [comment]
where is mtrand.pyx located?
