### ISSUE TITLE
Error while executing run.py

### ISSUE THREAD

**Issue by raghavsharma775** [vadi95/Signature-Verification#5]
Hi,
 I have encountered an error while executing  run.py file.
The error is:
Traceback (most recent call last):
  File "run.py", line 118, in <module>
    get_contour_features(preprocessed_image.copy(), display=False)
  File "run.py", line 76, in get_contour_features
    im2, contours, hierarchy = cv2.findContours(im.copy(), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

Please correct it as soon as possible.
Email me at: raghavsharma775@gmail.com

**Comment by vadi95** [comment]
Added instructions to run the project. It should fix that error.

Closing issue. Reopen if you encounter it again.

**Comment by ghost** [comment]
It again shows the error:

ValueError                                Traceback (most recent call last)
<ipython-input-1-7e2ea9ec12e9> in <module>()
    127         hash = imagehash.phash(Image.open(image_path))
    128 
--> 129         aspect_ratio, bounding_rect_area, convex_hull_area, contours_area =             get_contour_features(preprocessed_image.copy(), display=False)
    130 
    131         hash = int(str(hash), 16)

<ipython-input-1-7e2ea9ec12e9> in get_contour_features(preprocessed_image, display)
     82         cv2.waitKey()
     83 
---> 84     _, contours, hierarchy = cv2.findContours(preprocessed_image.copy(), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
     85 
     86     if display:

ValueError: not enough values to unpack (expected 3, got 2)

**Comment by vadi95** [comment]
Are you using docker or a virtual env?

**Comment by ghost** [comment]
I am using docker

**Comment by vadicn** [comment]
That's weird, it works for me

**Comment by ghost** [comment]
I am not able to understand what shall i do now.
