### ISSUE TITLE
getting value error  ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by ghost** [vadi95/Signature-Verification#6]

**Comment by ghost** [comment]
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by ghost** [comment]
ValueError                                Traceback (most recent call last)
<ipython-input-29-ae4b028a47e1> in <module>()
     25         hash = imagehash.phash(Image.open(image_path))
     26 
---> 27         aspect_ratio, bounding_rect_area, convex_hull_area, contours_area =             get_contour_features(preprocessed_image.copy(), display=False)
     28 
     29         hash = int(str(hash), 16)

<ipython-input-21-e39a25f3d2fa> in get_contour_features(im, display)
     28         cv2.waitKey()
     29 
---> 30     im2, contours, hierarchy = cv2.findContours(im.copy(), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
     31 
     32     if display:

ValueError: not enough values to unpack (expected 3, got 2)

**Comment by vadi95** [comment]
Added instructions to run the project. It should fix that error.

Closing issue. Reopen if you encounter it again.
